### ISSUE TITLE
Fix linting errors

### ISSUE THREAD

**Issue by Barabasbalazs** [flevi29/search_state#5]
Currently when running:

```zsh
deno lint
```

a lot of issues get reported.

```zsh
error[no-explicit-any]: `any` type is not allowed
  --> /home/balazs/Documents/search_state/src/hits_with_numbered_pagination.ts:55:50
   | 
55 |   T extends Record<string, any> = Record<string, any>,
   |                                                  ^^^
   = hint: Use a specific type other than `any`

  docs: https://lint.deno.land/rules/no-explicit-any
```
 
Seems like a lot of _any_ types are being used in the code. 
Either disable this warnings, or better address them.
For more qualitative code this should be fixed, so we can add this to the testing workflow as well.

**Comment by flevi29** [comment]
Fixed in latest commit https://github.com/flevi29/search_state/commit/70ec08d7d23701c13fd9b83de347aa8173350204
