### ISSUE TITLE
Add demo projects for other frameworks as well

### ISSUE THREAD

**Issue by Barabasbalazs** [flevi29/search_state#9]
To better illustrate the capabilities and use cases, I think it would be cool to add demo's with other frameworks as well (Vue, React, etc.)
Maybe we could for the [mini-dashboard](https://github.com/meilisearch/mini-dashboard) for meili and just switch out the [instantsearch](https://www.npmjs.com/package/react-instantsearch) dep for this package.

**Comment by flevi29** [comment]
> To better illustrate the capabilities and use cases, I think it would be cool to add demo's with other frameworks as well (Vue, React, etc.)

I feel like that's not the way to go. I wanted to have a demo project to easily test my changes on the web, interactively. Instead we should strive to make the project easily implementable, no matter the framework. Just try and document it as well as possible, the framework part is the responsibility of the package user, if they still have no idea what to do, they should learn their framework first.

> Maybe we could for the [mini-dashboard](https://github.com/meilisearch/mini-dashboard) for meili and just switch out the [instantsearch](https://www.npmjs.com/package/react-instantsearch) dep for this package.

Yeah I though about that. But that will take some time and convincing. There's a lot of work to do before that.
